### ISSUE TITLE
Modifier la mise en page du formulaire de recherche

### ISSUE THREAD

**Issue by lebouquetin** [BenoitEchernier/web#11]
Au lieu de 4 lignes (mots-clés, géolocalisation, distance, bouton "lancer la recherche"), mettre les différents champs sur une seule ligne : 

- mots-clés sur 40%, 
- ville sur 20%, 
- "distance" sur 20% (mettre un truc genre "et jusqu'à 20km"
- bouton "lancer la recherche" sur 20%

L'idée c'est qu'au final, le formulaire renseigné ressemble à quelque chose comme : 
python, postgresql à Grenoble - 38000 et jusqu'à 25km autour "filtrer"

Le thème s'appuyant sur Bootstrap, on s'appuiera sur les formulaires inline - http://getbootstrap.com/css/#forms

Note : on renomme aussi le bouton lancer la recherche par "filtrer" avec une icone "loupe" à l'intérieur <i class="fa fa-search"></i>

**Comment by BenoitEchernier** [comment]
Est-ce que je prévois un emplacement pour un champ permettant de choisir le tri préféré pour le filtrage ? (à savoir par date ou par pertinence).

**Comment by lebouquetin** [comment]
Oui vas-y
